name: physicson
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0+1
  stagexl: ^1.4.5

dev_dependencies:
  angular_test: ^2.3.0 
  build_runner: ^1.9.0
  build_test: ^0.10.12+1
  build_web_compilers: ^2.9.0
  pedantic: ^1.9.0
  test: ^1.6.3
